const express = require("express")
const router = express.Router()
const controller= require("../../controllers/client/checkout.controller")
const validate = require("../../validates/client/checkout.validate")
const vnpayController = require("../../controllers/client/vnpay.controller")
const authMiddleware = require("../../middlewares/client/auth.middleware")
router.get("/",validate.index,controller.index)
router.post("/order",validate.order,controller.order)
router.get("/success/:orderId",controller.success)
router.get("/vnpay-return",vnpayController.vnpayReturn)
router.get("/vnpay-ipn",vnpayController.vnpayIpn)
router.post("/pay-again",authMiddleware.requireAuth,vnpayController.payAgain)
module.exports =router