const homeRoutes = require("./home.route")
const productRoutes = require("./product.route")
const searchRoutes = require("./search.route")
const cartRoutes = require("./cart.route")
const checkoutRoutes = require("./checkout.route")
const userRoutes = require("./user.route")
const oauthRoutes = require("./oauth.route")
const cartMiddleware = require("../../middlewares/client/cart.middleware")
const categoryMiddleware = require("../../middlewares/client/category.middleware")
const userMiddleware = require("../../middlewares/client/user.middleware")
const settingMiddleware = require("../../middlewares/client/setting.middleware")
module.exports = (app) =>{
  app.use(categoryMiddleware.category)
  app.use(cartMiddleware.cartId)
  app.use(userMiddleware.infoUser)
  app.use(settingMiddleware.SettingGeneral)
  app.use("/api", homeRoutes)
  app.use("/api/products", productRoutes)
  app.use("/api/search", searchRoutes)
  app.use("/api/cart", cartRoutes)
  app.use("/api/checkout", checkoutRoutes)
  app.use("/api/user", userRoutes)
  app.use("/api/auth", oauthRoutes)
}