const adminRoutes = require("./dashboard.route")
const productRoutes = require("./product.route")
const productCategoryRoutes = require("./product-category.route")
const roleRoutes = require("./role.route")
const accountRoutes = require("./account.route")
const authRoutes = require("./auth.route")
const oauthRoutes = require("./oauth.route")
const myAccountRoutes = require("./my-account.route")
const orderRoutes = require("./order.route")
const settingRoutes = require("./setting.route")
const reviewRoutes = require("./review.route")
const authController = require("../../controllers/admin/auth.controller")
const systemConfig = require("../../config/system")
const authMiddleware = require("../../middlewares/admin/auth.middleware")
module.exports = (app) =>{
  const PATH_ADMIN = systemConfig.prefixAdmin
  app.get("/api" + PATH_ADMIN + "/", authController.login)
  app.use("/api" + PATH_ADMIN + "/dashboard", authMiddleware.requireAuth, adminRoutes)
  app.use("/api" + PATH_ADMIN + '/products', authMiddleware.requireAuth, productRoutes)
  app.use("/api" + PATH_ADMIN + '/products-category', authMiddleware.requireAuth, productCategoryRoutes)
  app.use("/api" + PATH_ADMIN + '/roles', authMiddleware.requireAuth, roleRoutes)
  app.use("/api" + PATH_ADMIN + '/accounts', authMiddleware.requireAuth, accountRoutes)
  app.use("/api" + PATH_ADMIN + '/auth', authRoutes)
  app.use("/api" + PATH_ADMIN + '/auth', oauthRoutes)
  app.use("/api" + PATH_ADMIN + '/my-account', authMiddleware.requireAuth, myAccountRoutes)
  app.use("/api" + PATH_ADMIN + '/orders', authMiddleware.requireAuth, orderRoutes)
  app.use("/api" + PATH_ADMIN + '/settings', authMiddleware.requireAuth, settingRoutes)
  app.use("/api" + PATH_ADMIN + '/reviews', authMiddleware.requireAuth, reviewRoutes)
}